### ISSUE TITLE
Load lotus node doesn't see .safetensors only gguf

### ISSUE THREAD

**Issue by bobiblazeski** [kijai/ComfyUI-Lotus#8]
I downloaded the lotus models via manager, but whereever I put them node ignores, tried renameing them to ggug then it sees them but it returns error when it tries to load them

![gguf](https://github.com/user-attachments/assets/c342f955-130e-4cf4-ab26-f00a25c9e472)

**Comment by kijai** [comment]
Are you sure you have the models in `ComfyUI/models/diffusion_models`? That's where it looks for them.

**Comment by bobiblazeski** [comment]
Here's a screenshot

![difusion_models](https://github.com/user-attachments/assets/6599be7d-e6b4-4e6d-b6f2-4c0548ba821d)

and here are the unet models gguf
![unet](https://github.com/user-attachments/assets/007b73f5-ae78-43a6-b13c-e6ddb584029e)

if I rename safetensors to gguf it sees them
![renamed](https://github.com/user-attachments/assets/6bdc72f9-a3b7-4cb5-a550-e488a932af46)


I'm using 

ComfyUI: v0.3.8-1-gc441048
         (2024-12-19)
Manager: V2.55.5
On Ubuntu 24.10
 
I've added webui forge paths to load additional models

When I try to run it with renamed to .gguf model I got error 

LoadLotusModel
invalid load key, '\x18'.

**Comment by kijai** [comment]
Highly confusing, can't think of anything what would cause that from my end.. maybe some other custom node interfering?

**Comment by bobiblazeski** [comment]
OK will try with a fresh install for ComfyUI

**Comment by bobiblazeski** [comment]
Works on a fresh installation of comfyui, many thanks.
![lotus](https://github.com/user-attachments/assets/3e2b73f8-70f5-4f6b-94bc-dad05d72d0cc)
